# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Eymen Kurdoglu, your friendly neighborhood curious fella
email: eymenkurdoglu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
a few half-baked thoughts and ideas about, uhm, some stuff. mostly video calling/conferencing research, some machine learning/data science. and maybe some more later on.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://eymenkurdoglu.github.io" # the base hostname & protocol for your site
twitter_username: gereksizengerek
github_username:  eymenkurdoglu

# Build settings
markdown: kramdown
